version: '2'
services:
    angjsweb-app:
        image: angjsweb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://angjsweb-postgresql:5432/angjsweb
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    angjsweb-postgresql:
        extends:
            file: postgresql.yml
            service: angjsweb-postgresql
